// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RbxAQcdbpD_DpMVg3N1ZvYVtPxt5yzU',
    appId: '1:563142500451:web:d41b5c3a8dc3eed6e0d856',
    messagingSenderId: '563142500451',
    projectId: 'food-tracker-79f10',
    authDomain: 'food-tracker-79f10.firebaseapp.com',
    storageBucket: 'food-tracker-79f10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_RbxAQcdbpD_DpMVg3N1ZvYVtPxt5yzU',
    appId: '1:563142500451:android:d41b5c3a8dc3eed6e0d856',
    messagingSenderId: '563142500451',
    projectId: 'food-tracker-79f10',
    storageBucket: 'food-tracker-79f10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RbxAQcdbpD_DpMVg3N1ZvYVtPxt5yzU',
    appId: '1:563142500451:ios:d41b5c3a8dc3eed6e0d856',
    messagingSenderId: '563142500451',
    projectId: 'food-tracker-79f10',
    storageBucket: 'food-tracker-79f10.firebasestorage.app',
    iosBundleId: 'com.example.foodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_RbxAQcdbpD_DpMVg3N1ZvYVtPxt5yzU',
    appId: '1:563142500451:ios:d41b5c3a8dc3eed6e0d856',
    messagingSenderId: '563142500451',
    projectId: 'food-tracker-79f10',
    storageBucket: 'food-tracker-79f10.firebasestorage.app',
    iosBundleId: 'com.example.foodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_RbxAQcdbpD_DpMVg3N1ZvYVtPxt5yzU',
    appId: '1:563142500451:web:d41b5c3a8dc3eed6e0d856',
    messagingSenderId: '563142500451',
    projectId: 'food-tracker-79f10',
    authDomain: 'food-tracker-79f10.firebaseapp.com',
    storageBucket: 'food-tracker-79f10.firebasestorage.app',
  );
}
